// todo-list-wia-vue3/src/components/NewTodo.vue
<template>
  <div class="new-todo-box">
    <h3>Add new Todo</h3>
    <form>

      <div class="box1">
        <label for="newtitle">New Title</label>
        <input id="newtitle" type="text" v-model.trim="newTitle">
      </div>
      <div class="box2">
        <label>Date</label>
        <DatePicker class="add-date" v-model="newDate" ></Datepicker>
      </div>
      <button @click.prevent="addToDb()" class="btn btn-success btn-add ">Add</button>
    </form>
  </div>
</template>

<script>

  import DatePicker from 'vue3-persian-datetime-picker'
  export default {
    components: { DatePicker } ,
    data(){
      return {
        newTitle: '' ,
        newDate: '' ,

      }
    } ,
    methods : {
      addToDb(){
        let oldTodos = []
          oldTodos =  localStorage.getItem('todos') != null ? JSON.parse(localStorage.getItem('todos')) : []
          let todos = [{
          title : this.newTitle ,
          date : this.newDate ,
          status :false
        }]
        oldTodos = oldTodos.concat(todos)
        localStorage.setItem('todos' , JSON.stringify(oldTodos) )
        this.newTitle = ''
        this.newDate = ''
        alert("Todo Added Successful .")
      } ,
    }
  }
</script>

<style>
  .new-todo-box {
    width: 800px;
    margin: 0 auto ;
    border: 1px solid #eee;
    border-radius: 5px;
    padding: 10px 15px;
    text-align: center;
  }
  form {
    width: 100%;
  }
  form input#newtitle {
    display: block;
    width : 100% ;
    height: 35px;
    border: 1px solid #dadada;
    border-radius: 5px;
  }
  .add-date input {
    border: 1px solid #dadada;
    border-radius: 5px;
    height: 38px;
    border-left: none;
  }
  .box1,box2{
    margin: 15px 0;
  }
  .btn-add {
    margin-top: 20px;
  }
</style>

// todo-list-wai-react/src/components/NewTodo/NewTodo.js
import { useState } from 'react';
import './NewTodo.css'
import './../Header/Header'
import Header from './../Header/Header';

function NewTodo() {

  const [Title , setTitle ] = useState("") ;
  const [pickDate , setPickDate ] = useState("") ;

  let newTodo = [
    {
      id:Date.now() ,
      title:Title ,
      date:pickDate , 
      status:false
    }
  ]
  const oldTodo = localStorage.getItem('todos') !== null ? JSON.parse(localStorage.getItem('todos')) : []  ;

  let allTodo = oldTodo.concat(newTodo)

  const addToDb = (e)=> {
    e.preventDefault()
    if(Title !== "" && pickDate !== ""){

      localStorage.setItem('todos' , JSON.stringify(allTodo)) 

      setPickDate("")
      setTitle("")

      alert("Your Todo Added To List")

    }else {
      alert("Please Fill the Title and Date")
    }

  }

  return (
    <>
    <Header />
    <div className='container'>
      <form onSubmit={addToDb}>
        <label className='title'>
          <span>Title</span>
          <input type="text" onChange={(e)=> setTitle(e.target.value)} value={Title} />
        </label>

        <label>
          <span className='date'>Date</span>
          <input type="date"  onChange={(e) => setPickDate(e.target.value) } value={pickDate} />
        </label>

        <button >Add Todo</button>
      </form>
    </div>
    </>
  );
}

export default NewTodo;
